from typing import List, Dict
from .local_llm import get_local_ai

def find_relevant_clauses(clauses: List[Dict], query_text: str) -> List[Dict]:
    normalized_query = query_text.lower()
    matches = []

    for item in clauses:
        if (
            normalized_query in item["text"].lower()
            or normalized_query in item["title"].lower()
        ):
            matches.append(item)

    return matches

def answer_from_contract(clauses: List[Dict], question: str) -> str:
    matches = find_relevant_clauses(clauses, question)

    if not matches:
        return "The document does not appear to contain an answer to this specific inquiry."

    curated_context = "\n\n".join(
        [
            f"Article {c['clause_id']} - {c['title']}:\n{c['text'][:700]}"
            for c in matches
        ]
    )

    ai = get_local_ai()

    prompt = f"""
    You are a professional legal assistant. 
    Use the provided contract excerpts to answer the question concisely. 
    If the answer isn't in the text, clearly state that. 
    Do not synthesize information from outside the provided excerpts.
    
    Document Snippets:
    {curated_context}
    
    Search Query: {question}
    """

    try:
        answer = ai.generate(prompt, max_tokens=300)
        return answer if answer else "No answer could be generated by the local AI."
    except Exception as e:
        return f"Local QA failed: {str(e)}"
